/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoGradle;

import demo.pr.dto.Jarra;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	Jarra jarra = null;//new Jarra("jarraA",3,2);
    	//System.out.println(jarra.getCapacidad());
    	//System.out.println(jarra.capacidad);
        //
    	
//    	RuntimeException exe = null;
//    	throw exe;
    	
//    	Jarra[] jarrasArray = null;
//    	int longitud = jarrasArray.length; //Se lanzará NullPointerException aquí
//    	Jarra[] jarrasArray = null;
//    	Jarra jarraB = jarrasArray[1]; //Se lanzará NullPointerException aquí
    	
//    	Jarra jarraC = null;
//    	synchronized (jarraC) { //Se lanzará NullPointerException aquí
//    	    System.out.println("Este bloque es synchronized sobre una variable nula");
//    	}
    	
    	Jarra jarraD = null;
    	System.out.println(jarraD.nombre);
    	
    }
}
